### ISSUE TITLE
Create a gh-pages branch

### ISSUE THREAD

**Issue by Bernard-A** [openschc/openschc#11]
To push the documentation generated by sphinx, I would need an existing gh-pages branch on th main repository

**Comment by Bernard-A** [comment]
Reminder on how to make the branch : https://daler.github.io/sphinxdoc-test/includeme.html#set-up-separate-docs-repository

**Comment by dbarthel-ol** [comment]
I've read the page you refered us to.
I think this branch can be created in your own directory (git branch gh-pages) and it will be created in the openschc repo as the Pull Request is merged.
Or do you know that this is not true?

**Comment by dbarthel-ol** [comment]
Anyway, I just created the gh-pages branch on the GitHub repo. You can check it out.
