### ISSUE TITLE
pytestifying all tests

### ISSUE THREAD

**Issue by twatteyne** [openschc/openschc#111]
We need to have all tests written using the `pytest` so they can be run by GitHub Actions.

I see two locations for tests:
- the `test/` directory. The `README` suggest one needs to run the scripts directly but `test_frag.py` suggests `pytest` is used
- different `test_*.py` script at the root, which I believe should be run directly.

My approach would to migrate *all* tests into the `tests/` directory, using the `pytest` approach.

I can do the heavy-lifting, but @MarinoMtz, please indicate which tests we expect to run.

**Comment by MarinoMtz** [comment]
Yes, I agree.
For now we can take the test that are in src/tests, i'll add there the fragmentation ones there progressively

**Comment by twatteyne** [comment]
OK. What I will do is change the GitHub actions configuration so all tests from `test/` run continuously. I will also move test [test_compress.py](https://github.com/openschc/openschc/blob/develop/src/test_compress.py) under `test/` (and pytestify it).
