### ISSUE TITLE
rule format

### ISSUE THREAD

**Issue by ltn22** [openschc/openschc#12]
The rule format may have to change to allow several rules for fragmentation and compression for a specific device.

For me the constraints are:
- the rule must be the same in the device and in the core C/D
- in the core C/D we must easily look up for the rule of a specific device by its LPWAN @ 
- in the core C/D rules can be stored in a file (or in MongoDB)
- in the device the rule is easily associated to the device

In rulemanager.py, the rule is defined this way:

```python
    db = [
        {
            "devL2Addr": ..,
            "dstIID": ..,
            "comp": {
                    "ruleID": ..,
                    "ruleLength": ..,
                    "compression": { ...}
                },
            "fragSender": {
                    "ruleID": ..,
                    "ruleLength": ..,
                    "fragmentation": { ...}
                }
            "fragReceiver": {
                    "ruleID": ..,
                    "ruleLength": ..,
                    "fragmentation": { ...}
                }
        }, ...
    ]
```
In my view the structure should be more:

```python
    db = [
        {
            "devL2Addr": ..,
            "devIP": "   ",  # mandatory
             "rules": {
                [{
                      ruleID: xxx,
                      ruleLength: xxx, 
                      compression: {
                            [["fieldID", ..., ....],
                             ["ffffff", ...        ]
                     },
                    {
                      ruleID: xxx,
                      ruleLength: xxx, 
                      fragmentation: {
                           "direction": "up",
                           parameters....
                     }
                  }...
    
        }, 
        {.....}

 
    ]
```

**Comment by tanupoo** [comment]
My understanding from your view is like below.  Please correct me if I am misunderstanding.

- The "rules" key has the multiple "compression" rules.
- The "rules" key may have the "fragmentation" rule.  If so, it always has two "fragmentation" rules.
- ruleID/ruleLength must be a unique not only in the "rules", but also in the whole db.

In the device side,
- when it sends a packet, it asks the rule manager for the destination IP address in the packet, which is to be matched with "devIP".
- if a "rules" is found, it tries to apply each compression rule until completely matching a rule with the packet.
- then, compress the SCHC Packet if a fragmentation rule exists in the "rules" and needs to be applied.
- when it receives a data which is assumed to be SCHC fragments or a SCHC packet, it asks the rule manager for the data, which is to be matched with the ruleID/ruleLength in the head of the data.  If a rule in a "rules" is found, it assembles them or decompress it according to the rule.

In the translator side,
- when it receives a packet from a node in the Internet, it asks the rule manager for the destination IP address in the packet, which is to be matched with "devIP".
- if a "rules" is found, it does same as the device side.
- when it receives a data from a LPWA gateway or a network server, it asks the rule manager for the data, then same as the behavior in the device side.

**Comment by ltn22** [comment]
Done, the reference to old format should be removed. The main change is that now fragSender and fragReceiver has been merged into a single fragmentation rule and a direction keyword has been introduced to indicate if the SCHC F/R is F or R.
