### ISSUE TITLE
move develop to Master

### ISSUE THREAD

**Issue by ltn22** [openschc/openschc#140]
For many months Master as been quite and all the changes appears in the develop branch, with the following modifications:

- introduction of the coreconf format in the rule_manager
- add link to LNS through a proxy
- correct bugs in coap compression
- ICMPv6 ping message process

I propose you, for clarification to merge the develop to Master next week.

**Comment by adjih** [comment]
I have no objection, and there should be no problem in merging the branch as `develop` had been merged at some point.

 #117 can be done later, and #120 will be updated.

**Comment by ltn22** [comment]
Master has become the reference. It integrates all the last changes:
- new MO/CDA for ICMPv6
- datamodel with CORECONF

Develop can be removed.
