### ISSUE TITLE
uplink and downlink fragmentation

### ISSUE THREAD

**Issue by ltn22** [openschc/openschc#22]
in the current fragmentation rule, there is no indication if the rule msut be used uplink or downlink. A new tag must be added to tell the direction

**Comment by adjih** [comment]
Understood. 

In the code, this should be reflected in `protocol.SCHCProtocol': the node should know if it is device or application(server) by configuration.

(in the case that is not in SCHC use cases, where it is both, e.g. relaying: I guess the only solution would be to identify "device or app. server" based on sender L2 address).

**Comment by ltn22** [comment]
added to rule a mandatory new keyword
FRDirection that can be either UP or DW
