### ISSUE TITLE
no-compression RuleID is mandatory

### ISSUE THREAD

**Issue by dbarthel-ol** [openschc/openschc#45]
The source code and the documentation must be improved to mandate that a "no-compression" RuleID MUST be present in the Rule set.
Define an attribute for this special "compression" rule.

**Comment by ltn22** [comment]
Added in rulemanager-update branch. 

The no compression rule must look like this:

with the keywork NoCompression

no_compression = {
    "RuleID" : 13,
    "RuleIDLength": 4,
    "NoCompression" : []
}

print has also be updated.
