### ISSUE TITLE
client_server_simulation.txt

### ISSUE THREAD

**Issue by tanupoo** [openschc/openschc#49]
Does anyone know what client_server_simulation.txt is ?
frag_send.py contains below code.  Why and what ?

f = open("client_server_simulation.txt", "w+")

**Comment by adjih** [comment]
It was introduced with the client-server communication, after review by Olivier, the file is not useful (except for the purpose of logging).
The ".txt" file can be removed, and the f.write can be changed in some form of logging, I guess.

**Comment by tanupoo** [comment]
Thanks! I have commented them out.
