### ISSUE TITLE
type of prefix and iid

### ISSUE THREAD

**Issue by tanupoo** [openschc/openschc#64]
The type of prefix is in integer by Parser.parse(), but in bytes by the rule manager.  There is a part to convert into a type for comparison in the source code internally.  I think that It's better to keep it as a single type without converting the type.

Is is okey to adopt "bytes" type of prefix and IID in Parser.parse() ?

**Comment by ltn22** [comment]
sounds good, it was an integer for compactness in micropython, we don't care that much now.

**Comment by tanupoo** [comment]
Changed the type.
