### ISSUE TITLE
contextlib and micropython

### ISSUE THREAD

**Issue by tanupoo** [openschc/openschc#69]
It is not a case in general.  But, my micropython doesn't have contextlib.
Is it acceptable on your micropython ?  If not, the core SCHC codes which is under the src folder should have only features supported by micropython.

% micropython                                      
MicroPython v1.12-35-g10709846f on 2020-08-03; darwin version
Use Ctrl-D to exit, Ctrl-E for paste mode
>>> import sys
>>> sys.version_info
(3, 4, 0)

>>> import contextlib
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: no module named 'contextlib'
>>>

**Comment by OussamaOux** [comment]
Hello,
I have exactly the same issue, did you found any solution ?
I can't run openschc in my pycom because my micropython doesn't have contextlib.

**Comment by ltn22** [comment]
Hi 

I fear that openschc does not support any more micropython, may be the compression and decompression stuff is adapted, but the fragmentation has been developped only for python.

Laurent

**Comment by OussamaOux** [comment]
Thank you for replay,
yes exactly the openschc is not designed for micropython, I think it could be great if you support micropython in future !
