### ISSUE TITLE
GitHub Actions

### ISSUE THREAD

**Issue by twatteyne** [openschc/openschc#93]
add support for GitHub Actions to run all tests all the time

**Comment by Damola12345** [comment]
hi @twatteyne can i work on this task ?

**Comment by adjih** [comment]
The state of the tests is the following:
- The test [test_frag_new.py](https://github.com/openschc/openschc/tree/master/src/test_frag_new.py) is the basic fragmentation test. It used to work, but at one point there was a MIC check error, and current it does not find the fragmentation rule (?). The last problem should be easily fixable.
- The test  [test_compress.py](https://github.com/openschc/openschc/tree/master/src/test_compress.py) tests the compression from the RuleManager.
- There are several outdated files in src/test, and those tests were not quite comprehensive.
- The simulator was that I used at the end for fragmentation [examples/simulator](https://github.com/openschc/openschc/tree/master/examples/simulator) - this can be the basis for more automated tests with logs. (no longer finds the fragmentation rule see test_frag_new.py).
- The example  [examples/udp](https://github.com/openschc/openschc/tree/master/examples/udp) is another test that was run manually to test the code. It was never fully automated (requires 2 processes communicating through UDP, so there is a bit of set-up to do).
- The files prepared for a potential  [interop](https://github.com/openschc/openschc/tree/master/interop) can also be used as a basis for tests. At the same time as working on this part, @Oliv4945 had also set up automated CI on github in the past (should be the Travis yaml ?).
- The latest branch is `scapy`, with many developments. We need to check how it is tested @MarinoMtz  @ltn22

**Comment by twatteyne** [comment]
@adjih any update about this?

**Comment by twatteyne** [comment]
#110  fixes this
